from conditions.all_the_same import *
from conditions.common_features import *
from conditions.contains_all import *
from conditions.contains_kinds import *
from conditions.contains_objects import *
from conditions.empty_or_not_empty import *
from conditions.house_empty_slots import *
from conditions.identical_features import *
from conditions.no_of_empty_rooms import *
from conditions.not_contain_unless_repeated import *
from conditions.room_wall_color_matches_object_colors import *
