from decorum_generator.conditions.all_the_same import *
from decorum_generator.conditions.common_features import *
from decorum_generator.conditions.contains_all import *
from decorum_generator.conditions.contains_kinds import *
from decorum_generator.conditions.contains_objects import *
from decorum_generator.conditions.empty_or_not_empty import *
from decorum_generator.conditions.house_empty_slots import *
from decorum_generator.conditions.identical_features import *
from decorum_generator.conditions.no_of_empty_rooms import *
from decorum_generator.conditions.not_contain_unless_repeated import *
from decorum_generator.conditions.room_wall_color_matches_object_colors import *
